apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    kind: ClusterRole
    name: manager-role
  path: manager_role.yaml
- target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
  path: mutating_webhook_config.yaml
