apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: olmv1-system
resources:
- prometheus.yaml
- catalogd_service_monitor.yaml
- kubelet_service_monitor.yaml
- operator_controller_service_monitor.yaml
- prometheus_rule.yaml
- auth_token.yaml
- network_policy.yaml
- service.yaml
- rbac
replacements:
- source:
    kind: ServiceMonitor
    name: catalogd-controller-manager-metrics-monitor
    fieldPath: metadata.namespace
  targets:
  - select:
      kind: ServiceMonitor
      name: catalogd-controller-manager-metrics-monitor
    fieldPaths:
    - spec.endpoints.0.tlsConfig.serverName
    options:
      delimiter: '.'
      index: 1
  - select:
      kind: ServiceMonitor
      name: operator-controller-controller-manager-metrics-monitor
    fieldPaths:
    - spec.endpoints.0.tlsConfig.serverName
    options:
      delimiter: '.'
      index: 1
