apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: system
spec:
  logLevel: debug
  serviceAccountName: prometheus
  scrapeTimeout: 30s
  scrapeInterval: 1m
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
        type: RuntimeDefault
  ruleSelector: {}
  serviceDiscoveryRole: EndpointSlice
  serviceMonitorSelector: {}
