---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catalogd-manager-role
  namespace: openshift-catalogd
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
