---
# Source: olmv1/templates/rbac/rolebinding-olmv1-system-common-leader-election-rolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-leader-election-rolebinding
  namespace: openshift-catalogd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalogd-leader-election-role
subjects:
  - kind: ServiceAccount
    name: catalogd-controller-manager
    namespace: openshift-catalogd
