apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- path: manager_namespace_privileged.yaml
- path: manager_namespace_monitored.yaml
- path: manager_namespace_annotations.yaml
- target:
    kind: Service
    name: service
  path: manager_service.yaml
- target:
    kind: MutatingWebhookConfiguration
    name: mutating-webhook-configuration
  path: mutating_webhook_config.yaml
- target:
    kind: ClusterRole
    name: manager-role
  path: manager_role.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: manager_deployment_certs.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: manager_deployment_mount_etc_containers.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: manager_deployment_log_verbosity.yaml
- target:
    kind: Deployment
    name: controller-manager
  path: manager_deployment_node_selection.yaml
