apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-monitor-role
  labels:
    control-plane: operator-controller-controller-manager
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
