apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-monitor-rolebinding
  labels:
    control-plane: operator-controller-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-monitor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
