---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
