---
# Source: olmv1/templates/rbac/clusterrolebinding-common-proxy-rolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    olm.operatorframework.io/feature-set: standard
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: catalogd-proxy-role
subjects:
  - kind: ServiceAccount
    name: catalogd-controller-manager
    namespace: openshift-catalogd
