---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-metrics-monitor-rolebinding
  namespace: openshift-catalogd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: catalogd-metrics-monitor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
