---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: catalogserver-cert
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
  name: catalogd-service
  namespace: openshift-catalogd
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: webhook
      port: 9443
      protocol: TCP
      targetPort: 9443
    - name: metrics
      port: 7443
      protocol: TCP
      targetPort: 7443
  selector:
    control-plane: catalogd-controller-manager
