---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: catalogd-default-deny-all-traffic
  namespace: openshift-catalogd
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
