#!/bin/sh

if [ -z "${1}" ]; then
   echo "No destination specified"
   exit 1
fi

DEST=${1}

if [ -d /openshift/helm ]; then
    mkdir -p "${DEST}/helm/catalogd"
    cp -a /openshift/helm/* "${DEST}/helm/catalogd"
fi

