---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-controller-extension-viewer-role
rules:
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - extensions
    verbs:
      - get
      - list
      - watch
