---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-controller-manager-rolebinding
  namespace: openshift-operator-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: operator-controller-controller-manager
    namespace: openshift-operator-controller
