---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: operator-controller-openshift-ca
  namespace: openshift-operator-controller
