---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: operator-controller-cert
  labels:
    control-plane: operator-controller-controller-manager
  name: operator-controller-service
  namespace: openshift-operator-controller
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    control-plane: operator-controller-controller-manager
