# Default values for OLMv1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# List of components to include
options:
  operatorController:
    enabled: true
    deployment:
      image: ${OPERATOR_CONTROLLER_IMAGE}
  catalogd:
    enabled: false
  openshift:
    enabled: true

# This can be one of: standard or experimental
featureSet: standard

# The set of namespaces
namespaces:
  olmv1:
    name: openshift-operator-controller

# Deployment values for operator-controller
deployments:
  templateSpec:
    priorityClassName: system-cluster-critical
    securityContext:
      seLinuxOptions:
        type: spc_t
