apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-monitor-rolebinding
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-monitor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
