apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-monitor-role
  labels:
    app.kubernetes.io/name: catalogd
    app.kubernetes.io/part-of: olm
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
