---
# Source: olmv1/templates/openshift/configmap-trusted-ca.yml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/part-of: olm
  name: operator-controller-trusted-ca-bundle
  namespace: openshift-operator-controller
