---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-controller-operator-controller-clusterextension-editor-role
rules:
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clusterextensions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
