---
# Source: olmv1/templates/rbac/clusterrole-operator-controller-clusterextension-editor-role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  labels:
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/part-of: olm
  name: operator-controller-clusterextension-editor-role
rules:
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clusterextensions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
