---
# Source: olmv1/templates/rbac/rolebinding-olmv1-system-common-manager-rolebinding.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    olm.operatorframework.io/feature-set: experimental
  labels:
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/part-of: olm
  name: operator-controller-manager-rolebinding
  namespace: openshift-operator-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller-manager-role
subjects:
  - kind: ServiceAccount
    name: operator-controller-controller-manager
    namespace: openshift-operator-controller
