---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: operator-controller-default-deny-all-traffic
  namespace: openshift-operator-controller
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
