apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: olm
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/audit-version: v1.32
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.32
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/warn-version: v1.32
  name: openshift-operator-controller
  annotations:
    workload.openshift.io/allowed: management
