---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    control-plane: operator-controller-controller-manager
  name: operator-controller-metrics-monitor-role
  namespace: openshift-operator-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
