---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-controller-extension-editor-role
rules:
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - extensions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
