---
# Source: olmv1/templates/rbac/clusterrole-operator-controller-manager-role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-controller-manager-role
  labels:
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/part-of: olm
  annotations:
    olm.operatorframework.io/feature-set: standard
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clustercatalogs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clusterextensions
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clusterextensions/finalizers
    verbs:
      - update
  - apiGroups:
      - olm.operatorframework.io
    resources:
      - clusterextensions/status
    verbs:
      - patch
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - list
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
    verbs:
      - use
