---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    control-plane: operator-controller-controller-manager
  name: operator-controller-metrics-monitor-rolebinding
  namespace: openshift-operator-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operator-controller-metrics-monitor-role
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
