---
# Source: olmv1/templates/rbac/role-olmv1-system-operator-controller-manager-role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-controller-manager-role
  namespace: openshift-operator-controller
  labels:
    app.kubernetes.io/name: operator-controller
    app.kubernetes.io/part-of: olm
  annotations:
    olm.operatorframework.io/feature-set: standard
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
