---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/default-logs-container: manager
  labels:
    control-plane: operator-controller-controller-manager
  name: operator-controller-controller-manager
  namespace: openshift-operator-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: operator-controller-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
        openshift.io/required-scc: privileged
      labels:
        control-plane: operator-controller-controller-manager
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - ppc64le
                      - s390x
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      containers:
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=:8443
            - --leader-elect
            - --tls-cert=/var/certs/tls.crt
            - --tls-key=/var/certs/tls.key
            - --ca-certs-dir=/var/service-cas
            - --v=${LOG_VERBOSITY}
            - --global-pull-secret=openshift-config/pull-secret
          command:
            - /operator-controller
          image: ${OPERATOR_CONTROLLER_IMAGE}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/cache
              name: cache
            - mountPath: /var/certs
              name: operator-controller-certs
              readOnly: true
            - mountPath: /var/service-cas
              name: service-cas
              readOnly: true
            - mountPath: /etc/containers
              name: etc-containers
              readOnly: true
            - mountPath: /etc/docker
              name: etc-docker
              readOnly: true
            - mountPath: /etc/pki
              name: etc-pki
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: operator-controller-controller-manager
      terminationGracePeriodSeconds: 10
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 120
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 120
      volumes:
        - emptyDir: {}
          name: cache
        - name: operator-controller-certs
          secret:
            optional: false
            secretName: operator-controller-cert
        - configMap:
            items:
              - key: service-ca.crt
                path: service-ca.crt
            name: openshift-service-ca.crt
            optional: false
          name: service-cas
        - hostPath:
            path: /etc/containers
            type: Directory
          name: etc-containers
        - hostPath:
            path: /etc/docker
            type: Directory
          name: etc-docker
        - hostPath:
            path: /etc/pki
            type: Directory
          name: etc-pki
      priorityClassName: system-cluster-critical
